language: clojure
lein: 2.9.1
sudo: false

before_script:
  - make fmt

script:
  - make lint
  - make cover

cache:
  directories:
    - $HOME/.clj

jdk:
  - openjdk11

# after_success:
#  - make coveralls
